remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "mint"  # Was "air", now using a friendlier color palette

locale                   : "en-US"
title                    : "Donald Loveland"
title_separator          : "-"
subtitle                 : "Graph Learning, Recommender Systems, and Personalization"
name                     : "Donald Loveland"
description              : "Personal website for Donald Loveland. Donald is a Ph.D. student in Computer Science at University of Michigan, Ann Arbor and advised by Danai Koutra. Research interests include interpretable, robust, and fair deep learning on graphs, as well as recommender systems."
url                      : "https://donaldloveland.github.io"
repository               : "dloveland/donaldloveland.github.io"

masthead_title           : "Donald Loveland"
teaser                   : "/assets/images/preview.png"
og_image                 : "/assets/images/preview.png"

words_per_minute         : 200


author:
  name             : "Donald Loveland"
  avatar           : "/assets/images/loveland_headshot.jpg"
  bio              : "Computer Science Ph.D. student at University of Michigan, Ann Arbor."
  location         : "Ann Arbor, Michigan"
  email            : "dlovelan@umich.edu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:dlovelan@umich.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/donald-loveland/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dloveland"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/donald-loveland/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dloveland"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments:
      share: true
      related: true
  - scope:
      path: ""
      type: pubs
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true

include: ["_pages"]
